# https://taskfile.dev
version: "3"

tasks:
  compile-grammar:
    desc: Compile ANTLR grammar
    cmds:
      - uvx --from antlr4-tools antlr4 -Dlanguage=Go -o parser bpftrace.g4

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  test-tools:
    desc: Run tests against bpftrace/tools
    cmds:
      - go test ./...

  build:
    desc: Build the btfmt binary
    cmds:
      - go build ./cmd/btfmt

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
