# https://taskfile.dev
version: "3"

tasks:
  compile-grammar:
    desc: Compile bpftrace.g4 grammar file using ANTLR4
    cmds:
      - uvx --from antlr4-tools antlr4 -Dlanguage=Go -o parser bpftrace.g4
