package lsp

type ProbeDefinition struct {
	Name        string
	Category    string
	Description string
	Arguments   []string
}

var commonKprobes = []ProbeDefinition{
	{Name: "vfs_read", Category: "VFS", Description: "Read from file"},
	{Name: "vfs_readv", Category: "VFS", Description: "Read vector from file"},
	{Name: "vfs_readlink", Category: "VFS", Description: "Read symbolic link"},
	{Name: "vfs_write", Category: "VFS", Description: "Write to file"},
	{Name: "vfs_open", Category: "VFS", Description: "Open file"},
	{Name: "vfs_create", Category: "VFS", Description: "Create file"},
	{Name: "vfs_unlink", Category: "VFS", Description: "Delete file"},
	{Name: "vfs_rename", Category: "VFS", Description: "Rename file"},
	{Name: "vfs_mkdir", Category: "VFS", Description: "Create directory"},
	{Name: "vfs_rmdir", Category: "VFS", Description: "Remove directory"},
	{Name: "vfs_fsync", Category: "VFS", Description: "Sync file to disk"},
	{Name: "vfs_getattr", Category: "VFS", Description: "Get file attributes"},
	{Name: "vfs_setattr", Category: "VFS", Description: "Set file attributes"},
	{Name: "vfs_stat", Category: "VFS", Description: "Get file statistics"},
	{Name: "vfs_lstat", Category: "VFS", Description: "Get file statistics (don't follow links)"},
	{Name: "vfs_fstat", Category: "VFS", Description: "Get file statistics by fd"},

	{Name: "do_filp_open", Category: "VFS", Description: "Open file by name"},
	{Name: "do_filp_fstat", Category: "VFS", Description: "Get file stat"},
	{Name: "do_sys_open", Category: "VFS", Description: "System call open handler"},

	{Name: "blk_account_io_start", Category: "Block", Description: "Block I/O start"},
	{Name: "blk_account_io_done", Category: "Block", Description: "Block I/O completion"},
	{Name: "submit_bio", Category: "Block", Description: "Submit bio request"},
	{Name: "submit_bio_wait", Category: "Block", Description: "Submit bio and wait"},
	{Name: "blk_update_request", Category: "Block", Description: "Update block request"},
	{Name: "blk_mq_start_request", Category: "Block", Description: "Start block MQ request"},
	{Name: "blk_mq_complete_request", Category: "Block", Description: "Complete block MQ request"},

	{Name: "tcp_connect", Category: "Network", Description: "TCP connect"},
	{Name: "tcp_retransmit_skb", Category: "Network", Description: "TCP retransmit"},
	{Name: "tcp_set_state", Category: "Network", Description: "TCP state change"},
	{Name: "tcp_v4_syn_recv_sock", Category: "Network", Description: "TCP IPv4 SYN received"},
	{Name: "tcp_v6_syn_recv_sock", Category: "Network", Description: "TCP IPv6 SYN received"},
	{Name: "tcp_sendmsg", Category: "Network", Description: "TCP send message"},
	{Name: "tcp_recvmsg", Category: "Network", Description: "TCP receive message"},
	{Name: "tcp_close", Category: "Network", Description: "TCP close"},
	{Name: "tcp_v4_destroy_sock", Category: "Network", Description: "Destroy TCP socket"},
	{Name: "tcp_v6_destroy_sock", Category: "Network", Description: "Destroy TCP IPv6 socket"},

	{Name: "udp_sendmsg", Category: "Network", Description: "UDP send message"},
	{Name: "udp_recvmsg", Category: "Network", Description: "UDP receive message"},
	{Name: "udp_send_skb", Category: "Network", Description: "UDP send skb"},

	{Name: "ip_rcv", Category: "Network", Description: "IP receive"},
	{Name: "ip_local_deliver", Category: "Network", Description: "IP local deliver"},
	{Name: "ip_output", Category: "Network", Description: "IP output"},
	{Name: "ip_queue_xmit", Category: "Network", Description: "IP queue transmit"},

	{Name: "netif_receive_skb", Category: "Network", Description: "Network interface receive"},
	{Name: "napi_gro_receive", Category: "Network", Description: "NAPI GRO receive"},
	{Name: "dev_queue_xmit", Category: "Network", Description: "Device queue transmit"},
	{Name: "net_dev_start_xmit", Category: "Network", Description: "Start network transmit"},
	{Name: "net_dev_xmit", Category: "Network", Description: "Network device transmit"},

	{Name: "kmalloc", Category: "Memory", Description: "Allocate kernel memory"},
	{Name: "kfree", Category: "Memory", Description: "Free kernel memory"},
	{Name: "kzalloc", Category: "Memory", Description: "Allocate zeroed kernel memory"},
	{Name: "krealloc", Category: "Memory", Description: "Reallocate kernel memory"},
	{Name: "__alloc_pages", Category: "Memory", Description: "Allocate pages"},
	{Name: "__free_pages", Category: "Memory", Description: "Free pages"},
	{Name: "get_free_pages", Category: "Memory", Description: "Get free pages"},
	{Name: "free_pages", Category: "Memory", Description: "Free pages"},
	{Name: "alloc_pages_current", Category: "Memory", Description: "Allocate pages current"},
	{Name: "page_alloc", Category: "Memory", Description: "Allocate page"},
	{Name: "page_free", Category: "Memory", Description: "Free page"},

	{Name: "swap_readpage", Category: "Memory", Description: "Swap read page"},
	{Name: "swap_writepage", Category: "Memory", Description: "Swap write page"},
	{Name: "swap_free", Category: "Memory", Description: "Free swap"},
	{Name: "swap_cache_free", Category: "Memory", Description: "Free swap cache"},

	{Name: "handle_mm_fault", Category: "Memory", Description: "Handle memory fault"},
	{Name: "__do_page_fault", Category: "Memory", Description: "Page fault handler"},
	{Name: "do_wp_page", Category: "Memory", Description: "Write protect page"},
	{Name: "do_anonymous_page", Category: "Memory", Description: "Anonymous page fault"},

	{Name: "do_fork", Category: "Process", Description: "Create process"},
	{Name: "do_exit", Category: "Process", Description: "Exit process"},
	{Name: "do_group_exit", Category: "Process", Description: "Group exit"},
	{Name: "do_execve", Category: "Process", Description: "Execute program"},
	{Name: "do_execveat", Category: "Process", Description: "Execute program at"},
	{Name: "wake_up_process", Category: "Process", Description: "Wake up process"},
	{Name: "try_to_wake_up", Category: "Process", Description: "Try to wake up"},
	{Name: "schedule", Category: "Process", Description: "Schedule process"},
	{Name: "context_switch", Category: "Process", Description: "Context switch"},
	{Name: "finish_task_switch", Category: "Process", Description: "Finish task switch"},

	{Name: "oom_kill_process", Category: "Process", Description: "OOM kill process"},
	{Name: "out_of_memory", Category: "Process", Description: "Out of memory handler"},

	{Name: "sys_open", Category: "Syscall", Description: "Open syscall"},
	{Name: "sys_openat", Category: "Syscall", Description: "Openat syscall"},
	{Name: "sys_read", Category: "Syscall", Description: "Read syscall"},
	{Name: "sys_write", Category: "Syscall", Description: "Write syscall"},
	{Name: "sys_close", Category: "Syscall", Description: "Close syscall"},
	{Name: "sys_stat", Category: "Syscall", Description: "Stat syscall"},
	{Name: "sys_fstat", Category: "Syscall", Description: "Fstat syscall"},
	{Name: "sys_lstat", Category: "Syscall", Description: "Lstat syscall"},
	{Name: "sys_mmap", Category: "Syscall", Description: "Mmap syscall"},
	{Name: "sys_munmap", Category: "Syscall", Description: "Munmap syscall"},
	{Name: "sys_brk", Category: "Syscall", Description: "Brk syscall"},
	{Name: "sys_execve", Category: "Syscall", Description: "Execve syscall"},
	{Name: "sys_fork", Category: "Syscall", Description: "Fork syscall"},
	{Name: "sys_clone", Category: "Syscall", Description: "Clone syscall"},
	{Name: "sys_exit", Category: "Syscall", Description: "Exit syscall"},
	{Name: "sys_wait4", Category: "Syscall", Description: "Wait4 syscall"},
	{Name: "sys_getpid", Category: "Syscall", Description: "Getpid syscall"},
	{Name: "sys_getppid", Category: "Syscall", Description: "Getppid syscall"},

	{Name: "cap_capable", Category: "Security", Description: "Check capability"},
	{Name: "security_inode_permission", Category: "Security", Description: "Check inode permission"},
	{Name: "security_file_permission", Category: "Security", Description: "Check file permission"},
	{Name: "security_task_setuid", Category: "Security", Description: "Set task uid"},

	{Name: "d_lookup", Category: "DCache", Description: "Dentry cache lookup"},
	{Name: "d_alloc", Category: "DCache", Description: "Allocate dentry"},
	{Name: "dput", Category: "DCache", Description: "Put dentry"},
	{Name: "d_instantiate", Category: "DCache", Description: "Instantiate dentry"},
	{Name: "lookup_fast", Category: "DCache", Description: "Fast lookup"},
	{Name: "lookup_slow", Category: "DCache", Description: "Slow lookup"},

	{Name: "do_page_read", Category: "File", Description: "Read page from file"},
	{Name: "do_page_write", Category: "File", Description: "Write page to file"},
	{Name: "generic_file_read_iter", Category: "File", Description: "Generic file read iterator"},
	{Name: "generic_file_write_iter", Category: "File", Description: "Generic file write iterator"},
	{Name: "generic_file_buffered_read", Category: "File", Description: "Buffered file read"},

	{Name: "skb_copy_datagram_iter", Category: "Network", Description: "Copy SKB data to iterator"},
	{Name: "skb_clone", Category: "Network", Description: "Clone SKB"},
	{Name: "skb_copy", Category: "Network", Description: "Copy SKB"},
	{Name: "kfree_skb", Category: "Network", Description: "Free SKB"},
	{Name: "consume_skb", Category: "Network", Description: "Consume SKB"},
	{Name: "__kfree_skb", Category: "Network", Description: "Free SKB (internal)"},
}

var commonTracepoints = []ProbeDefinition{
	{Name: "syscalls:sys_enter_read", Category: "Syscalls", Description: "Enter read syscall", Arguments: []string{"fd", "buf", "count"}},
	{Name: "syscalls:sys_exit_read", Category: "Syscalls", Description: "Exit read syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_write", Category: "Syscalls", Description: "Enter write syscall", Arguments: []string{"fd", "buf", "count"}},
	{Name: "syscalls:sys_exit_write", Category: "Syscalls", Description: "Exit write syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_open", Category: "Syscalls", Description: "Enter open syscall", Arguments: []string{"filename", "flags", "mode"}},
	{Name: "syscalls:sys_exit_open", Category: "Syscalls", Description: "Exit open syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_openat", Category: "Syscalls", Description: "Enter openat syscall", Arguments: []string{"dirfd", "pathname", "flags", "mode"}},
	{Name: "syscalls:sys_exit_openat", Category: "Syscalls", Description: "Exit openat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_openat2", Category: "Syscalls", Description: "Enter openat2 syscall", Arguments: []string{"dirfd", "pathname", "how", "size"}},
	{Name: "syscalls:sys_exit_openat2", Category: "Syscalls", Description: "Exit openat2 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_close", Category: "Syscalls", Description: "Enter close syscall", Arguments: []string{"fd"}},
	{Name: "syscalls:sys_exit_close", Category: "Syscalls", Description: "Exit close syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_stat", Category: "Syscalls", Description: "Enter stat syscall", Arguments: []string{"filename", "statbuf"}},
	{Name: "syscalls:sys_exit_stat", Category: "Syscalls", Description: "Exit stat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fstat", Category: "Syscalls", Description: "Enter fstat syscall", Arguments: []string{"fd", "statbuf"}},
	{Name: "syscalls:sys_exit_fstat", Category: "Syscalls", Description: "Exit fstat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_lstat", Category: "Syscalls", Description: "Enter lstat syscall", Arguments: []string{"filename", "statbuf"}},
	{Name: "syscalls:sys_exit_lstat", Category: "Syscalls", Description: "Exit lstat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_newfstatat", Category: "Syscalls", Description: "Enter newfstatat syscall", Arguments: []string{"dirfd", "pathname", "statbuf", "flag"}},
	{Name: "syscalls:sys_exit_newfstatat", Category: "Syscalls", Description: "Exit newfstatat syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_mmap", Category: "Syscalls", Description: "Enter mmap syscall", Arguments: []string{"addr", "length", "prot", "flags", "fd", "offset"}},
	{Name: "syscalls:sys_exit_mmap", Category: "Syscalls", Description: "Exit mmap syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_munmap", Category: "Syscalls", Description: "Enter munmap syscall", Arguments: []string{"addr", "length"}},
	{Name: "syscalls:sys_exit_munmap", Category: "Syscalls", Description: "Exit munmap syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_mprotect", Category: "Syscalls", Description: "Enter mprotect syscall", Arguments: []string{"start", "len", "prot"}},
	{Name: "syscalls:sys_exit_mprotect", Category: "Syscalls", Description: "Exit mprotect syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_brk", Category: "Syscalls", Description: "Enter brk syscall", Arguments: []string{"brk"}},
	{Name: "syscalls:sys_exit_brk", Category: "Syscalls", Description: "Exit brk syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_execve", Category: "Syscalls", Description: "Enter execve syscall", Arguments: []string{"filename", "argv", "envp"}},
	{Name: "syscalls:sys_exit_execve", Category: "Syscalls", Description: "Exit execve syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_execveat", Category: "Syscalls", Description: "Enter execveat syscall", Arguments: []string{"dirfd", "pathname", "argv", "envp", "flags"}},
	{Name: "syscalls:sys_exit_execveat", Category: "Syscalls", Description: "Exit execveat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fork", Category: "Syscalls", Description: "Enter fork syscall"},
	{Name: "syscalls:sys_exit_fork", Category: "Syscalls", Description: "Exit fork syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_clone", Category: "Syscalls", Description: "Enter clone syscall", Arguments: []string{"clone_flags", "newsp", "parent_tidptr", "child_tidptr", "tls"}},
	{Name: "syscalls:sys_exit_clone", Category: "Syscalls", Description: "Exit clone syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_vfork", Category: "Syscalls", Description: "Enter vfork syscall"},
	{Name: "syscalls:sys_exit_vfork", Category: "Syscalls", Description: "Exit vfork syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_exit", Category: "Syscalls", Description: "Enter exit syscall", Arguments: []string{"error_code"}},
	{Name: "syscalls:sys_exit_exit", Category: "Syscalls", Description: "Exit exit syscall"},
	{Name: "syscalls:sys_enter_exit_group", Category: "Syscalls", Description: "Enter exit_group syscall", Arguments: []string{"error_code"}},
	{Name: "syscalls:sys_exit_exit_group", Category: "Syscalls", Description: "Exit exit_group syscall"},
	{Name: "syscalls:sys_enter_wait4", Category: "Syscalls", Description: "Enter wait4 syscall", Arguments: []string{"pid", "stat_addr", "options", "ru"}},
	{Name: "syscalls:sys_exit_wait4", Category: "Syscalls", Description: "Exit wait4 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_waitid", Category: "Syscalls", Description: "Enter waitid syscall", Arguments: []string{"which", "upid", "infop", "options", "ru"}},
	{Name: "syscalls:sys_exit_waitid", Category: "Syscalls", Description: "Exit waitid syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_getpid", Category: "Syscalls", Description: "Enter getpid syscall"},
	{Name: "syscalls:sys_exit_getpid", Category: "Syscalls", Description: "Exit getpid syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_getppid", Category: "Syscalls", Description: "Enter getppid syscall"},
	{Name: "syscalls:sys_exit_getppid", Category: "Syscalls", Description: "Exit getppid syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_gettid", Category: "Syscalls", Description: "Enter gettid syscall"},
	{Name: "syscalls:sys_exit_gettid", Category: "Syscalls", Description: "Exit gettid syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_socket", Category: "Syscalls", Description: "Enter socket syscall", Arguments: []string{"family", "type", "protocol"}},
	{Name: "syscalls:sys_exit_socket", Category: "Syscalls", Description: "Exit socket syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_connect", Category: "Syscalls", Description: "Enter connect syscall", Arguments: []string{"fd", "uservaddr", "addrlen"}},
	{Name: "syscalls:sys_exit_connect", Category: "Syscalls", Description: "Exit connect syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_accept", Category: "Syscalls", Description: "Enter accept syscall", Arguments: []string{"fd", "upeer_sockaddr", "upeer_addrlen"}},
	{Name: "syscalls:sys_exit_accept", Category: "Syscalls", Description: "Exit accept syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_accept4", Category: "Syscalls", Description: "Enter accept4 syscall", Arguments: []string{"fd", "upeer_sockaddr", "upeer_addrlen", "flags"}},
	{Name: "syscalls:sys_exit_accept4", Category: "Syscalls", Description: "Exit accept4 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_sendto", Category: "Syscalls", Description: "Enter sendto syscall", Arguments: []string{"fd", "buff", "len", "flags", "addr", "addr_len"}},
	{Name: "syscalls:sys_exit_sendto", Category: "Syscalls", Description: "Exit sendto syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_recvfrom", Category: "Syscalls", Description: "Enter recvfrom syscall", Arguments: []string{"fd", "ubuf", "size", "flags", "addr", "addr_len"}},
	{Name: "syscalls:sys_exit_recvfrom", Category: "Syscalls", Description: "Exit recvfrom syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_sendmsg", Category: "Syscalls", Description: "Enter sendmsg syscall", Arguments: []string{"fd", "msg", "flags"}},
	{Name: "syscalls:sys_exit_sendmsg", Category: "Syscalls", Description: "Exit sendmsg syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_recvmsg", Category: "Syscalls", Description: "Enter recvmsg syscall", Arguments: []string{"fd", "msg", "flags"}},
	{Name: "syscalls:sys_exit_recvmsg", Category: "Syscalls", Description: "Exit recvmsg syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_dup", Category: "Syscalls", Description: "Enter dup syscall", Arguments: []string{"fildes"}},
	{Name: "syscalls:sys_exit_dup", Category: "Syscalls", Description: "Exit dup syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_dup2", Category: "Syscalls", Description: "Enter dup2 syscall", Arguments: []string{"oldfd", "newfd"}},
	{Name: "syscalls:sys_exit_dup2", Category: "Syscalls", Description: "Exit dup2 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_dup3", Category: "Syscalls", Description: "Enter dup3 syscall", Arguments: []string{"oldfd", "newfd", "flags"}},
	{Name: "syscalls:sys_exit_dup3", Category: "Syscalls", Description: "Exit dup3 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pipe", Category: "Syscalls", Description: "Enter pipe syscall", Arguments: []string{"fildes"}},
	{Name: "syscalls:sys_exit_pipe", Category: "Syscalls", Description: "Exit pipe syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pipe2", Category: "Syscalls", Description: "Enter pipe2 syscall", Arguments: []string{"fildes", "flags"}},
	{Name: "syscalls:sys_exit_pipe2", Category: "Syscalls", Description: "Exit pipe2 syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_epoll_create", Category: "Syscalls", Description: "Enter epoll_create syscall", Arguments: []string{"size"}},
	{Name: "syscalls:sys_exit_epoll_create", Category: "Syscalls", Description: "Exit epoll_create syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_epoll_create1", Category: "Syscalls", Description: "Enter epoll_create1 syscall", Arguments: []string{"flags"}},
	{Name: "syscalls:sys_exit_epoll_create1", Category: "Syscalls", Description: "Exit epoll_create1 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_epoll_ctl", Category: "Syscalls", Description: "Enter epoll_ctl syscall", Arguments: []string{"epfd", "op", "fd", "event"}},
	{Name: "syscalls:sys_exit_epoll_ctl", Category: "Syscalls", Description: "Exit epoll_ctl syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_epoll_wait", Category: "Syscalls", Description: "Enter epoll_wait syscall", Arguments: []string{"epfd", "events", "maxevents", "timeout"}},
	{Name: "syscalls:sys_exit_epoll_wait", Category: "Syscalls", Description: "Exit epoll_wait syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_epoll_pwait", Category: "Syscalls", Description: "Enter epoll_pwait syscall", Arguments: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize"}},
	{Name: "syscalls:sys_exit_epoll_pwait", Category: "Syscalls", Description: "Exit epoll_pwait syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_select", Category: "Syscalls", Description: "Enter select syscall", Arguments: []string{"n", "inp", "outp", "exp", "tvp"}},
	{Name: "syscalls:sys_exit_select", Category: "Syscalls", Description: "Exit select syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pselect6", Category: "Syscalls", Description: "Enter pselect6 syscall", Arguments: []string{"n", "inp", "outp", "exp", "tsp", "sig"}},
	{Name: "syscalls:sys_exit_pselect6", Category: "Syscalls", Description: "Exit pselect6 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_poll", Category: "Syscalls", Description: "Enter poll syscall", Arguments: []string{"ufds", "nfds", "timeout"}},
	{Name: "syscalls:sys_exit_poll", Category: "Syscalls", Description: "Exit poll syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_ppoll", Category: "Syscalls", Description: "Enter ppoll syscall", Arguments: []string{"ufds", "nfds", "tsp", "sigmask", "sigsetsize"}},
	{Name: "syscalls:sys_exit_ppoll", Category: "Syscalls", Description: "Exit ppoll syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_lseek", Category: "Syscalls", Description: "Enter lseek syscall", Arguments: []string{"fd", "offset", "whence"}},
	{Name: "syscalls:sys_exit_lseek", Category: "Syscalls", Description: "Exit lseek syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pread64", Category: "Syscalls", Description: "Enter pread64 syscall", Arguments: []string{"fd", "buf", "count", "pos"}},
	{Name: "syscalls:sys_exit_pread64", Category: "Syscalls", Description: "Exit pread64 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pwrite64", Category: "Syscalls", Description: "Enter pwrite64 syscall", Arguments: []string{"fd", "buf", "count", "pos"}},
	{Name: "syscalls:sys_exit_pwrite64", Category: "Syscalls", Description: "Exit pwrite64 syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_readv", Category: "Syscalls", Description: "Enter readv syscall", Arguments: []string{"fd", "vec", "vlen"}},
	{Name: "syscalls:sys_exit_readv", Category: "Syscalls", Description: "Exit readv syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_writev", Category: "Syscalls", Description: "Enter writev syscall", Arguments: []string{"fd", "vec", "vlen"}},
	{Name: "syscalls:sys_exit_writev", Category: "Syscalls", Description: "Exit writev syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_preadv", Category: "Syscalls", Description: "Enter preadv syscall", Arguments: []string{"fd", "vec", "vlen", "pos_l", "pos_h"}},
	{Name: "syscalls:sys_exit_preadv", Category: "Syscalls", Description: "Exit preadv syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_pwritev", Category: "Syscalls", Description: "Enter pwritev syscall", Arguments: []string{"fd", "vec", "vlen", "pos_l", "pos_h"}},
	{Name: "syscalls:sys_exit_pwritev", Category: "Syscalls", Description: "Exit pwritev syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_mkdir", Category: "Syscalls", Description: "Enter mkdir syscall", Arguments: []string{"pathname", "mode"}},
	{Name: "syscalls:sys_exit_mkdir", Category: "Syscalls", Description: "Exit mkdir syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_mkdirat", Category: "Syscalls", Description: "Enter mkdirat syscall", Arguments: []string{"dirfd", "pathname", "mode"}},
	{Name: "syscalls:sys_exit_mkdirat", Category: "Syscalls", Description: "Exit mkdirat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_rmdir", Category: "Syscalls", Description: "Enter rmdir syscall", Arguments: []string{"pathname"}},
	{Name: "syscalls:sys_exit_rmdir", Category: "Syscalls", Description: "Exit rmdir syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_unlink", Category: "Syscalls", Description: "Enter unlink syscall", Arguments: []string{"pathname"}},
	{Name: "syscalls:sys_exit_unlink", Category: "Syscalls", Description: "Exit unlink syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_unlinkat", Category: "Syscalls", Description: "Enter unlinkat syscall", Arguments: []string{"dirfd", "pathname", "flags"}},
	{Name: "syscalls:sys_exit_unlinkat", Category: "Syscalls", Description: "Exit unlinkat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_rename", Category: "Syscalls", Description: "Enter rename syscall", Arguments: []string{"oldname", "newname"}},
	{Name: "syscalls:sys_exit_rename", Category: "Syscalls", Description: "Exit rename syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_renameat", Category: "Syscalls", Description: "Enter renameat syscall", Arguments: []string{"olddirfd", "oldname", "newdirfd", "newname"}},
	{Name: "syscalls:sys_exit_renameat", Category: "Syscalls", Description: "Exit renameat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_renameat2", Category: "Syscalls", Description: "Enter renameat2 syscall", Arguments: []string{"olddirfd", "oldname", "newdirfd", "newname", "flags"}},
	{Name: "syscalls:sys_exit_renameat2", Category: "Syscalls", Description: "Exit renameat2 syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_chdir", Category: "Syscalls", Description: "Enter chdir syscall", Arguments: []string{"filename"}},
	{Name: "syscalls:sys_exit_chdir", Category: "Syscalls", Description: "Exit chdir syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fchdir", Category: "Syscalls", Description: "Enter fchdir syscall", Arguments: []string{"fd"}},
	{Name: "syscalls:sys_exit_fchdir", Category: "Syscalls", Description: "Exit fchdir syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_getcwd", Category: "Syscalls", Description: "Enter getcwd syscall", Arguments: []string{"buf", "size"}},
	{Name: "syscalls:sys_exit_getcwd", Category: "Syscalls", Description: "Exit getcwd syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_chmod", Category: "Syscalls", Description: "Enter chmod syscall", Arguments: []string{"filename", "mode"}},
	{Name: "syscalls:sys_exit_chmod", Category: "Syscalls", Description: "Exit chmod syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fchmod", Category: "Syscalls", Description: "Enter fchmod syscall", Arguments: []string{"fd", "mode"}},
	{Name: "syscalls:sys_exit_fchmod", Category: "Syscalls", Description: "Exit fchmod syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fchmodat", Category: "Syscalls", Description: "Enter fchmodat syscall", Arguments: []string{"dirfd", "pathname", "mode"}},
	{Name: "syscalls:sys_exit_fchmodat", Category: "Syscalls", Description: "Exit fchmodat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_chown", Category: "Syscalls", Description: "Enter chown syscall", Arguments: []string{"filename", "user", "group"}},
	{Name: "syscalls:sys_exit_chown", Category: "Syscalls", Description: "Exit chown syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fchown", Category: "Syscalls", Description: "Enter fchown syscall", Arguments: []string{"fd", "user", "group"}},
	{Name: "syscalls:sys_exit_fchown", Category: "Syscalls", Description: "Exit fchown syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fchownat", Category: "Syscalls", Description: "Enter fchownat syscall", Arguments: []string{"dirfd", "pathname", "user", "group", "flags"}},
	{Name: "syscalls:sys_exit_fchownat", Category: "Syscalls", Description: "Exit fchownat syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_lchown", Category: "Syscalls", Description: "Enter lchown syscall", Arguments: []string{"filename", "user", "group"}},
	{Name: "syscalls:sys_exit_lchown", Category: "Syscalls", Description: "Exit lchown syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_sync", Category: "Syscalls", Description: "Enter sync syscall"},
	{Name: "syscalls:sys_exit_sync", Category: "Syscalls", Description: "Exit sync syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_syncfs", Category: "Syscalls", Description: "Enter syncfs syscall", Arguments: []string{"fd"}},
	{Name: "syscalls:sys_exit_syncfs", Category: "Syscalls", Description: "Exit syncfs syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fsync", Category: "Syscalls", Description: "Enter fsync syscall", Arguments: []string{"fd"}},
	{Name: "syscalls:sys_exit_fsync", Category: "Syscalls", Description: "Exit fsync syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fdatasync", Category: "Syscalls", Description: "Enter fdatasync syscall", Arguments: []string{"fd"}},
	{Name: "syscalls:sys_exit_fdatasync", Category: "Syscalls", Description: "Exit fdatasync syscall", Arguments: []string{"ret"}},

	{Name: "syscalls:sys_enter_flock", Category: "Syscalls", Description: "Enter flock syscall", Arguments: []string{"fd", "cmd"}},
	{Name: "syscalls:sys_exit_flock", Category: "Syscalls", Description: "Exit flock syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_lockf", Category: "Syscalls", Description: "Enter lockf syscall", Arguments: []string{"fd", "cmd", "len"}},
	{Name: "syscalls:sys_exit_lockf", Category: "Syscalls", Description: "Exit lockf syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_fcntl", Category: "Syscalls", Description: "Enter fcntl syscall", Arguments: []string{"fd", "cmd", "arg"}},
	{Name: "syscalls:sys_exit_fcntl", Category: "Syscalls", Description: "Exit fcntl syscall", Arguments: []string{"ret"}},
	{Name: "syscalls:sys_enter_ioctl", Category: "Syscalls", Description: "Enter ioctl syscall", Arguments: []string{"fd", "cmd", "arg"}},
	{Name: "syscalls:sys_exit_ioctl", Category: "Syscalls", Description: "Exit ioctl syscall", Arguments: []string{"ret"}},

	{Name: "sched:sched_switch", Category: "Scheduler", Description: "Task switch"},
	{Name: "sched:sched_wakeup", Category: "Scheduler", Description: "Task wakeup"},
	{Name: "sched:sched_wakeup_new", Category: "Scheduler", Description: "New task wakeup"},
	{Name: "sched:sched_process_fork", Category: "Scheduler", Description: "Process fork"},
	{Name: "sched:sched_process_exec", Category: "Scheduler", Description: "Process exec"},
	{Name: "sched:sched_process_exit", Category: "Scheduler", Description: "Process exit"},
	{Name: "sched:sched_process_wait", Category: "Scheduler", Description: "Process wait"},
	{Name: "sched:sched_migrate_task", Category: "Scheduler", Description: "Task migration"},
	{Name: "sched:sched_move_numa", Category: "Scheduler", Description: "NUMA task move"},
	{Name: "sched:sched_stick_numa", Category: "Scheduler", Description: "NUMA stick"},
	{Name: "sched:sched_pi_setprio", Category: "Scheduler", Description: "Priority inheritance setprio"},
	{Name: "sched:sched_waking", Category: "Scheduler", Description: "Task waking"},

	{Name: "net:net_dev_xmit", Category: "Network", Description: "Network device transmit"},
	{Name: "net:net_dev_queue", Category: "Network", Description: "Network device queue"},
	{Name: "net:netif_receive_skb", Category: "Network", Description: "Network receive SKB"},
	{Name: "net:netif_rx", Category: "Network", Description: "Network receive"},
	{Name: "net:napi_gro_receive_entry", Category: "Network", Description: "NAPI GRO receive entry"},
	{Name: "net:napi_gro_receive_exit", Category: "Network", Description: "NAPI GRO receive exit"},

	{Name: "irq:irq_handler_entry", Category: "IRQ", Description: "IRQ handler entry"},
	{Name: "irq:irq_handler_exit", Category: "IRQ", Description: "IRQ handler exit"},
	{Name: "irq:softirq_entry", Category: "IRQ", Description: "SoftIRQ entry"},
	{Name: "irq:softirq_exit", Category: "IRQ", Description: "SoftIRQ exit"},
	{Name: "irq:softirq_raise", Category: "IRQ", Description: "SoftIRQ raise"},

	{Name: "timer:timer_init", Category: "Timer", Description: "Timer init"},
	{Name: "timer:timer_start", Category: "Timer", Description: "Timer start"},
	{Name: "timer:timer_expire_entry", Category: "Timer", Description: "Timer expire entry"},
	{Name: "timer:timer_expire_exit", Category: "Timer", Description: "Timer expire exit"},
	{Name: "timer:hrtimer_init", Category: "Timer", Description: "High-res timer init"},
	{Name: "timer:hrtimer_start", Category: "Timer", Description: "High-res timer start"},

	{Name: "block:block_rq_issue", Category: "Block", Description: "Block request issue"},
	{Name: "block:block_rq_insert", Category: "Block", Description: "Block request insert"},
	{Name: "block:block_rq_complete", Category: "Block", Description: "Block request complete"},
	{Name: "block:block_rq_requeue", Category: "Block", Description: "Block request requeue"},
	{Name: "block:block_bio_bounce", Category: "Block", Description: "Block bio bounce"},
	{Name: "block:block_bio_complete", Category: "Block", Description: "Block bio complete"},
	{Name: "block:block_bio_queue", Category: "Block", Description: "Block bio queue"},
	{Name: "block:block_getrq", Category: "Block", Description: "Block get request"},
	{Name: "block:block_plug", Category: "Block", Description: "Block plug"},
	{Name: "block:block_unplug", Category: "Block", Description: "Block unplug"},
	{Name: "block:block_split", Category: "Block", Description: "Block split"},
	{Name: "block:block_remap", Category: "Block", Description: "Block remap"},

	{Name: "writeback:writeback_start", Category: "Writeback", Description: "Writeback start"},
	{Name: "writeback:writeback_written", Category: "Writeback", Description: "Writeback written"},
	{Name: "writeback:writeback_queue", Category: "Writeback", Description: "Writeback queue"},
	{Name: "writeback:writeback_exec", Category: "Writeback", Description: "Writeback exec"},
	{Name: "writeback:writeback_pages_written", Category: "Writeback", Description: "Pages written"},
	{Name: "writeback:writeback_nowork", Category: "Writeback", Description: "No work to do"},
	{Name: "writeback:writeback_wait", Category: "Writeback", Description: "Writeback wait"},
	{Name: "writeback:writeback_inode_template", Category: "Writeback", Description: "Inode template"},
	{Name: "writeback:writeback_single_inode", Category: "Writeback", Description: "Single inode writeback"},

	{Name: "kmem:kmalloc", Category: "Kmem", Description: "Kernel memory allocate"},
	{Name: "kmem:kmem_cache_alloc", Category: "Kmem", Description: "Cache allocate"},
	{Name: "kmem:mm_page_alloc", Category: "Kmem", Description: "Page allocate"},
	{Name: "kmem:mm_page_free", Category: "Kmem", Description: "Page free"},
	{Name: "kmem:mm_page_free_batched", Category: "Kmem", Description: "Batch page free"},
	{Name: "kmem:rss_stat", Category: "Kmem", Description: "RSS statistics"},

	{Name: "vmscan:mm_vmscan_direct_reclaim_begin", Category: "VMScan", Description: "Direct reclaim begin"},
	{Name: "vmscan:mm_vmscan_direct_reclaim_end", Category: "VMScan", Description: "Direct reclaim end"},
	{Name: "vmscan:mm_vmscan_kswapd_wake", Category: "VMScan", Description: "Kswapd wake"},
	{Name: "vmscan:mm_vmscan_kswapd_sleep", Category: "VMScan", Description: "Kswapd sleep"},
	{Name: "vmscan:mm_vmscan_wakeup_kswapd", Category: "VMScan", Description: "Wakeup kswapd"},
	{Name: "vmscan:mm_shrink_slab_start", Category: "VMScan", Description: "Shrink slab start"},
	{Name: "vmscan:mm_shrink_slab_end", Category: "VMScan", Description: "Shrink slab end"},
}

var softwareEvents = []ProbeDefinition{
	{Name: "cpu-clock", Category: "Software", Description: "CPU clock events"},
	{Name: "task-clock", Category: "Software", Description: "Task clock events"},
	{Name: "page-faults", Category: "Software", Description: "Page fault count"},
	{Name: "page-faults-user", Category: "Software", Description: "User page faults"},
	{Name: "context-switches", Category: "Software", Description: "Context switches"},
	{Name: "cpu-migrations", Category: "Software", Description: "CPU migrations"},
	{Name: "alignment-faults", Category: "Software", Description: "Alignment faults"},
	{Name: "emulation-faults", Category: "Software", Description: "Emulation faults"},
	{Name: "dummy", Category: "Software", Description: "Dummy events"},
	{Name: "bpf-output", Category: "Software", Description: "BPF program output"},
	{Name: "cgroup-switches", Category: "Software", Description: "Cgroup switches"},
}

var hardwareEvents = []ProbeDefinition{
	{Name: "cpu-cycles", Category: "Hardware", Description: "CPU cycles"},
	{Name: "instructions", Category: "Hardware", Description: "Instructions retired"},
	{Name: "cache-references", Category: "Hardware", Description: "Cache references"},
	{Name: "cache-misses", Category: "Hardware", Description: "Cache misses"},
	{Name: "branch-instructions", Category: "Hardware", Description: "Branch instructions"},
	{Name: "branch-misses", Category: "Hardware", Description: "Branch misses"},
	{Name: "bus-cycles", Category: "Hardware", Description: "Bus cycles"},
	{Name: "stalled-cycles-frontend", Category: "Hardware", Description: "Frontend stalled cycles"},
	{Name: "stalled-cycles-backend", Category: "Hardware", Description: "Backend stalled cycles"},
	{Name: "ref-cycles", Category: "Hardware", Description: "Reference cycles"},

	{Name: "L1-dcache-loads", Category: "Cache", Description: "L1 data cache loads"},
	{Name: "L1-dcache-load-misses", Category: "Cache", Description: "L1 data cache load misses"},
	{Name: "L1-dcache-stores", Category: "Cache", Description: "L1 data cache stores"},
	{Name: "L1-dcache-store-misses", Category: "Cache", Description: "L1 data cache store misses"},
	{Name: "L1-dcache-prefetches", Category: "Cache", Description: "L1 data cache prefetches"},
	{Name: "L1-dcache-prefetch-misses", Category: "Cache", Description: "L1 data cache prefetch misses"},
	{Name: "L1-icache-loads", Category: "Cache", Description: "L1 instruction cache loads"},
	{Name: "L1-icache-load-misses", Category: "Cache", Description: "L1 instruction cache load misses"},
	{Name: "LLC-loads", Category: "Cache", Description: "Last-level cache loads"},
	{Name: "LLC-load-misses", Category: "Cache", Description: "Last-level cache load misses"},
	{Name: "LLC-stores", Category: "Cache", Description: "Last-level cache stores"},
	{Name: "LLC-store-misses", Category: "Cache", Description: "Last-level cache store misses"},
	{Name: "LLC-prefetches", Category: "Cache", Description: "Last-level cache prefetches"},
	{Name: "LLC-prefetch-misses", Category: "Cache", Description: "Last-level cache prefetch misses"},

	{Name: "dTLB-loads", Category: "TLB", Description: "Data TLB loads"},
	{Name: "dTLB-load-misses", Category: "TLB", Description: "Data TLB load misses"},
	{Name: "dTLB-stores", Category: "TLB", Description: "Data TLB stores"},
	{Name: "dTLB-store-misses", Category: "TLB", Description: "Data TLB store misses"},
	{Name: "dTLB-prefetches", Category: "TLB", Description: "Data TLB prefetches"},
	{Name: "dTLB-prefetch-misses", Category: "TLB", Description: "Data TLB prefetch misses"},
	{Name: "iTLB-loads", Category: "TLB", Description: "Instruction TLB loads"},
	{Name: "iTLB-load-misses", Category: "TLB", Description: "Instruction TLB load misses"},
	{Name: "branch-loads", Category: "Branch", Description: "Branch loads"},
	{Name: "branch-load-misses", Category: "Branch", Description: "Branch load misses"},
}

func getProbeDefinitions(probeType string) []ProbeDefinition {
	switch probeType {
	case "kprobe", "kretprobe":
		return commonKprobes
	case "tracepoint":
		return commonTracepoints
	case "software":
		return softwareEvents
	case "hardware":
		return hardwareEvents
	case "uprobe", "uretprobe", "usdt":
		return nil
	default:
		return nil
	}
}
