#!/usr/bin/env python3
"""Generate the embedded tracepoint completion catalog."""

import argparse
import pathlib
import re


TRACE_SYSTEM = re.compile(r"^\s*#define\s+TRACE_SYSTEM\s+(\S+)", re.MULTILINE)
TRACE_EVENT = re.compile(
    r"^\s*(TRACE_EVENT(?:_[A-Z0-9_]+)?|DEFINE_EVENT(?:_[A-Z0-9_]+)?)"
    r"\s*\(\s*([A-Za-z0-9_]+)\s*(?:,\s*([A-Za-z0-9_]+))?",
    re.MULTILINE,
)
SYSCALL = re.compile(r"^\s*#define\s+__NR_([A-Za-z0-9_]+)\s+\d+", re.MULTILINE)
EVENT_MODIFIERS = {"TRACE_EVENT_FLAGS", "TRACE_EVENT_PERF_PERM"}


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//.*", "", text)


def strip_preprocessor_definitions(text: str) -> str:
    kept = []
    in_definition = False
    for line in text.splitlines():
        if in_definition:
            in_definition = line.rstrip().endswith("\\")
            continue
        if line.lstrip().startswith("#define"):
            in_definition = line.rstrip().endswith("\\")
            continue
        kept.append(line)
    return "\n".join(kept)


def header_tracepoints(events_dir: pathlib.Path) -> set[str]:
    targets = set()
    for path in sorted(events_dir.glob("*.h")):
        text = strip_comments(path.read_text(encoding="utf-8"))
        system_match = TRACE_SYSTEM.search(text)
        if system_match is None:
            continue
        system = system_match.group(1)
        body = strip_preprocessor_definitions(text)
        for match in TRACE_EVENT.finditer(body):
            macro, first, second = match.groups()
            if macro in EVENT_MODIFIERS:
                continue
            event = second if macro.startswith("DEFINE_EVENT") else first
            if event is not None:
                targets.add(f"{system}:{event}")
    return targets


def syscall_tracepoints(paths: list[pathlib.Path]) -> set[str]:
    targets = set()
    for path in paths:
        text = path.read_text(encoding="utf-8")
        for syscall in SYSCALL.findall(text):
            if syscall == "syscalls":
                continue
            targets.add(f"syscalls:sys_enter_{syscall}")
            targets.add(f"syscalls:sys_exit_{syscall}")
    return targets


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kernel-tree", type=pathlib.Path, required=True)
    parser.add_argument(
        "--syscall-header", type=pathlib.Path, action="append", default=[]
    )
    parser.add_argument("--source", required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    events_dir = args.kernel_tree / "include/trace/events"
    if not events_dir.is_dir():
        parser.error(f"trace event headers not found: {events_dir}")
    targets = header_tracepoints(events_dir)
    targets.update(syscall_tracepoints(args.syscall_header))

    lines = [
        "# Generated by scripts/generate_tracepoint_catalog.py.",
        f"# Source: {args.source}",
        "# Entries are completion suggestions and may not exist on every kernel.",
        *sorted(targets),
    ]
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
